apiVersion: v1
kind: Service
metadata:
  name: logicapp-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30090 # You can specify a port in the range 30000-32767
  type: NodePort

